baseURL = "https://www.example.com"
languageCode = "zh-cn"
title = "ç§‹æ°´"
theme = "hugo-digital-garden-theme"
themesdir = "themes"
copyright = "ç§‹æ°´ Â©"
ignorefiles = [ "content/template" ]

[params]
  name = "ç§‹æ°´"
  description = "ç§‘æŠ€å’Œé­”æ³•æ´ªæµçš„äº¤æ±‡ğŸŒŠ"
  initials = "ç§‹æ°´"
  googleAnalytics = ""
  dateFormat = "2006-01-02"

[menu]
  [[menu.main]]
    name = "æ•°å­—æµ·æ´‹"
    url = "/garden/"
    weight = 1
  [[menu.main]]
    name = "é¡¹ç›®"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "å…³äº"
    url = "/about/"
    weight = 4


[taxonomies]
  garden_tags = 'garden_tags'
  project_tags = 'project_tags'
  library_tags = 'library_tags'


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = 'github'
    wrapStandAloneImageWithinParagraph = true
    [markup.goldmark.parser.attribute]
      block = false
      title = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'